### ISSUE TITLE
Blog Post for Earthquake Relief Projects

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/giveth-planning#1208] opened 2023-02-08 18:34 UTC
Let's create a quick and simple post that highlights all the projects we have related to this natural disaster, so we have a one-stop shop for supporting this cause.

The idea will then be to create a banner to put on the homepage and link to this blog post.

**Comment by danelsuga** [comment] 2023-02-08 19:04
I'll work on this asap (I'm roughly 13 hours) unless @NikolaCreatrix can do it sooner since it's urgent? Meanwhile Nikola and @WhyldWanderer share the projects here? Thanks!

**Comment by WhyldWanderer** [comment] 2023-02-08 19:24
https://giveth.io/project/gnosisdao-earthquake-relief
https://giveth.io/project/banklessdao-turkey-disaster-relief-fund

**Comment by ahmadabugosh** [comment] 2023-02-08 19:27
@c0ric0ri @MoeNick Can we also make this into a landing page template? Remember we spoke about this before, making a landing page for projects where we just have a banner on top and a filter we add to the projects page (so we can easily spin up these kind of pages for causes).

**Comment by WhyldWanderer** [comment] 2023-02-08 19:27
Working on getting them verified now.. 
I imagine we can reward retroactively as we have done it in the past but I wouldnt promise GIVbacks until they are confirmed verified... I will notify you here when they are.

Will there be a way to add projects to the blogpost as they come in? how would taht work? 
Im sure there will be more

**Comment by c0ric0ri** [comment] 2023-02-08 19:36
Hey @ahmadabugosh I was on a call with @MoeNick this morning and he said the filtering isn't ready. So that's why we thought about using a blog post to replace the landing page concept for now, and just linking to the projects. We can write it quickly and post on Medium easily, and edit if needed to add more projects.

However I suppose we could also do the same on a landing page - but is it just as easy to do the above things?

**Comment by danelsuga** [comment] 2023-02-08 19:38
@WhyldWanderer yes already-published post can be edited to add more projects for sure.

**Comment by danelsuga** [comment] 2023-02-08 19:39
Oops! 🤣 I see I'm late to the answer-this-question party. 

> @WhyldWanderer yes already-published post can be edited to add more projects for sure.

**Comment by ahmadabugosh** [comment] 2023-02-08 19:41
@c0ric0ri  I see, yeah a landing page on our site might be better until we figure out filtering if we can make a simple one, like the [gitcoin](https://giveth.io/gitcoingrants) one (just some text with links to the projects), to keep people on our platform + for SEO.

**Comment by MoeNick** [comment] 2023-02-08 19:41
For banner we need content to assign to @rodricastillo9013 and put it in home page

**Comment by MoeNick** [comment] 2023-02-08 19:45
> @c0ric0ri  I see, yeah a landing page on our site might be better until we figure out filtering if we can make a simple one, like the [gitcoin](https://giveth.io/gitcoingrants) one (just some text with links to the projects), to keep people on our platform + for SEO. 

Hey @ahmadabugosh this is possible but we may get blocked by designers. I don't know whether @mosaeedi or @Tosinolawale can change their priorities for this one.

**Comment by c0ric0ri** [comment] 2023-02-08 20:08
Ok @MoeNick when could you confirm design capacity/priorities?

**Comment by MoeNick** [comment] 2023-02-08 20:15
> Ok @MoeNick when could you confirm design capacity/priorities?

I'll call @mosaeedi tomorrow morning my time, and get back to you. However because this is a not a routine workflow I suggest following up the blogpost.

**Comment by danelsuga** [comment] 2023-02-09 07:38
https://docs.google.com/document/d/1hYJUqTIkyOd_6CKeJ_Pcj4WKKdOeD_St_CLRGFT6U4o/edit?usp=sharing

**Comment by danelsuga** [comment] 2023-02-09 08:18
@clara-zi @ahmadabugosh 
could you review the earthquake piece so we can publish it asap? It looks like I might be able to put it up without going through @laurenluz 
Working on it at the moment.
Otherwise it'll be about six more hours...
I'd love to do it now. Every minute counts today.
We're hitting the end of when survivors statistically can still be found (3 days).

**Comment by ahmadabugosh** [comment] 2023-02-09 09:14
@danelsuga Left a few comments

**Comment by danelsuga** [comment] 2023-02-09 12:54
I have published it! 

https://medium.com/giveth/ways-to-help-earthquake-victims-in-turkey-and-syria-on-giveth-155d7855164

I had @ahmadabugosh  and @clara-zi  for review. I did not yet get a banner from @rodricastillo9013. I made a temporary one.

I really wanted to publish this asap. I will make any changes needed, as we get more projects and other input.

Let's please get some t-threads out of this asap.

**Comment by rodricastillo9013** [comment] 2023-02-09 13:38
![Donate banner](https://user-images.githubusercontent.com/61791380/217827816-1b69e7fc-ddcc-4efe-b050-f7339d2c6923.png)
I have made this Banner, tell me if it is ok! @danelsuga

**Comment by danelsuga** [comment] 2023-02-09 13:39
Thank you, @rodricastillo9013 !!

**Closed by danelsuga** 2023-02-09 13:39 UTC

**Comment by c0ric0ri** [comment] 2023-02-13 20:24
https://medium.com/giveth/ways-to-help-earthquake-victims-in-turkey-and-syria-on-giveth-155d7855164

**Comment by c0ric0ri** [comment] 2023-02-20 17:31
@danelsuga since the Gnosis project is terminated (it had about a 1 week timeline), can you add an updated note to the blog post?

**Comment by danelsuga** [comment] 2023-02-20 17:32
Got it.

**Comment by danelsuga** [comment] 2023-02-20 17:37
Done.
