### ISSUE TITLE
Find a solidity dev

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-planning#36] opened 2020-12-28 05:27 UTC
We need a solidity dev to lead the development of the smart contracts for the GIV token, liquidity mining program, and airdrop to past patrons.

**Comment by Danibelle** [comment] 2020-12-28 13:37
I'm seeing a lot more connection with MetaGame for Giveth coming up, perhaps we can tap into RaidGuild over there for support on this..

**Comment by jamespfarrell** [comment] 2020-12-28 13:39
I could deploy the token pretty easily.

Depending on the requirements for the liquidity mining, we could fork and redeploy the [PRIMEDAO liquidity mining](https://medium.com/primedao/primes-first-liquidity-mining-program-b8e4abb6c63) setup. I share an office with the lead dev, so that could happen quickly.

**Comment by willyogo** [comment] 2021-01-17 15:53
Gabi from 1hive and aragon can cover our solidity needs for launch requirements 🎉

**Comment by willyogo** [comment] 2021-02-17 05:03
Update: we no longer have Gabi. Edu is taking care of the token, vesting, liquidity mining, and airdrop contracts. We need to find a solidity dev to fork and modify the mStable staking contract

**Comment by ForestSoleil** [comment] 2021-03-03 14:55
Determined a plan to work around not requiring a solidity dev

**Comment by Danibelle** [comment] 2021-04-07 21:38
Yooooo..   Kevin OOooo is collecting names of Devs looking for work, and of projects looking for Devs..

**Comment by WhyldWanderer** [comment] 2021-04-21 22:26
Finalized Role Description:
https://www.notion.so/giveth/Solidity-Developer-Role-Description-b3ab2556e7bb4715b83e5d97bcd6ac7d

**Comment by ForestSoleil** [comment] 2021-04-21 22:27
^ Notion doc Ashley shared has been approved by Griff and Dani. Ready for outreach!

@WhyldWanderer doing some personal outreach on Discord and Panvala.
@laurenluz sharing on Twitter.
@divine-comedian sharing on Reddit.

Any other channels - please comment to track them here in this issue. Thanks!

**Comment by laurenluz** [comment] 2021-05-12 18:28
search ongoing, link to job posting: https://docs.giveth.io/jobs/

and on crypto jobs: https://cryptojobslist.com/jobs/lead-solidity-smart-contract-developer-at-giveth-remote

**Comment by laurenluz** [comment] 2021-05-12 18:37
closing because this is essentially a duplicate of #123

**Closed by laurenluz** 2021-05-12 18:37 UTC
