### ISSUE TITLE
Updating "Meet the team"

### ISSUE THREAD

**Issue by danelsuga** [Giveth/giveth-planning#792] opened 2022-07-05 10:27 UTC
![meet our team.png](https://images.zenhubusercontent.com/6066d509782b4d63df5cd761/013c5537-7474-4c3d-9407-d1aad0e04865)

@SymSL 's comment: 
I agree, would be great if new team members could be added even if they are just generic images instead of photos. I am not sure who has access to the back end of the website but this could be done by someone in comms, or by HR?  Maybe the dev team will have an easy suggestion for this

**Comment by MoeNick** [comment] 2022-07-25 19:13
Thanks, you moved this :)

**Comment by laurenluz** [comment] 2022-07-26 14:14
@divine-comedian can you link to the spreadsheet that has the nrGIV recipients from last round? 

Then @SymSL or @danelsuga - would one you be down to take that info and then make an open call to ask if any elginle people want to be added? You'll need their photo & title...

Then please make clear suggestions as to who should be removed, and who should be added + their relevant info (photo & title).

Once that's done we can move this issue back to development to implement.

**Comment by divine-comedian** [comment] 2022-07-26 21:43
https://docs.google.com/spreadsheets/d/1Kp8WqRwDGyORqaDcXpeGR2PnhVTMKlTdU-eDRWeDBN8/edit?usp=sharing

**Comment by laurenluz** [comment] 2022-07-30 00:34
@SymSL @danelsuga @c0ric0ri  - can any of you take this one?

**Comment by danelsuga** [comment] 2022-07-30 03:10
Can do tomorrow.

**Comment by danelsuga** [comment] 2022-07-30 21:09
OK, I'm looking at this now. I misread the task. I can't do this in any reasonable time in the near future. I'm also not sure this is a good approach? My feeling is that we don't need to feature team members as such since it does require such frequent updating. But if some one has the bandwidth, that's great. I def do not. At least not at the moment.

**Comment by oyealmond** [comment] 2023-06-23 21:07
@laurenluz I have a question, what happens when someone transfer an issue to another board? That means that the best is close the issue in this board?

**Comment by laurenluz** [comment] 2023-06-30 18:01
@oyealmond when you transfer an issue it moves from one repo to another... you don't need to close the issue anywhere, unless the issue is done/not planned.

I think we can just close this though... I don't think anyone has the bandswidth or desire to really do this.

**Closed by laurenluz** 2023-06-30 18:01 UTC
Labels: Content
