### ISSUE TITLE
GIVgarden

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-planning#307] opened 2021-07-07 16:55 UTC

**Comment by ForestSoleil** [comment] 2021-07-13 15:31
This is a duplicate of this issue: https://github.com/giveth/giveth-planning/issues/265

**Comment by laurenluz** [comment] 2021-09-01 19:51
@divine-comedian passing to you so you can write the GIVgarden skeleton and add appropriate gardens links from https://1hive.gitbook.io/gardens/

**Comment by divine-comedian** [comment] 2021-09-02 19:42
WIP - https://docs.google.com/document/d/1QVUqRAv0PLelIAEijwpYvUrfN1DWFcMzbC0BdP7uhKg/edit?usp=sharing

**Comment by divine-comedian** [comment] 2021-09-03 21:03
first draft ready for review at the link above :point_up: 

@laurenluz @WhyldWanderer @MiA-Engel

**Comment by laurenluz** [comment] 2021-09-14 21:34
@divine-comedian Thanks for putting that together. I reviewed and made a bunch of changes. Added Tao Voting & explainers, added the decision proposal option... and I changed the section about challenged proposals because it wasn't quite right (from my understanding). Left appropriate links so you can check it out.

After you incorporate edits, I think we should still hold off pushing to live until the GIVgarden is live on xDai and we feel satisfied because I think things are still subject change... And I think we'll have better links to documentation on things like Tao Voting by that point.

Anyway, really great work! I love the Proposal Lifecycle part, that will be really helpful for our users.

**Comment by laurenluz** [comment] 2021-09-15 01:47
ooh also plz add a bit about earning rewards from voting with tokens in the garden

**Comment by laurenluz** [comment] 2021-09-29 15:08
the earning rewards thing I think will be something like what Bright DAO is doing:

https://brightid.gitbook.io/brightid/bright/bright-dao/wrapping-bright

Griff said:
yes so staking GIV in the 100% GIV GIVfarm card will be the exact same smart contract action as wraping GIV tokens to use them to vote in the GIVgardens
so they will share the same APR
we wont need to do any extra work to calculate the APR for them 

Amin said:
Yesterday I studied 1Hive garden code and investigate how we can build the garden with same APR or 100% GIV Farm. 
It wasn't easy really and I planed a call with Sem. We could have a 2 hour call last night and evaluate solutions. At the end one is chosen and I will go for it, we have to change the 1Hive garden code a little bit to accept our already deployed unipool farm instead of deploying new one in garden creation process

**Comment by laurenluz** [comment] 2021-11-03 15:56
Need to add info from #367

Also need to explain what the user is "claiming" in the GIVgarden

**Comment by laurenluz** [comment] 2021-12-08 02:15
Made some comments on this. Do you think we should add our chosen parameters to the documentation?

**Comment by divine-comedian** [comment] 2021-12-09 13:59
> Made some comments on this. Do you think we should add our chosen parameters to the documentation?

Yes! I made a table and added them into the doc - just couldn't find the final proposal parameters - action deposit, challenge etc..

**Comment by laurenluz** [comment] 2021-12-10 16:02
![image](https://user-images.githubusercontent.com/75490971/145603889-bc5d6a0c-a9d7-4e09-86fc-0f5ce8b0b914.png)

**Comment by laurenluz** [comment] 2021-12-10 16:02
https://docs.google.com/spreadsheets/d/1nQrxI030dIDpS71N7HC5grrgOm6eIsPBLxsHi-Ud8GQ/edit#gid=0

**Comment by laurenluz** [comment] 2021-12-10 16:49
This is great. Made some minor fixes (added delegation). Would just fix up the table formatting then it's good to go!

**Comment by divine-comedian** [comment] 2021-12-10 17:29
the formatting will be in HTML/markdown so it won't matter too much how it looks now

**Comment by divine-comedian** [comment] 2021-12-10 18:53
LIVE 

https://docs.giveth.io/giveconomy/givgarden

**Closed** 2021-12-27 01:21 UTC
Labels: upload to docs
