### ISSUE TITLE
Comms Campaign on Iran Projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-planning#1038] opened 2022-11-21 14:33 UTC
Hey @oyealmond @NikolaCreatrix @WhyldWanderer @c0ric0ri  !

I was talking with @GriffGreen about this - apparently there are a lot of people creating Giveth projects to support Iran and it would be nice to do a kind of MTM-ish comms campaign.

At least a series of tweets for a few days highlighting the situation and different projects.

Wdyt?

I think the way forward if to get a list of the projects we want to hire via @NikolaCreatrix or @WhyldWanderer and then plan some tweets about it and maybe build it up a little more.

This is issues is a little for brainstorm so lmk what you all think.

**Comment by WhyldWanderer** [comment] 2022-11-21 18:37
Blog post? Then we can share on Twitter?

It would be cool to do it as the next MTM topic - that will be in January though... and maybe that is not soon enough?

I would love to support these projects in any way that we can! I also think that it is important to research them before we publicize them as there are often scams during times of crises.

Here is a list of the projects I have seen come through so far with a focus on supporting the situation in Iran:

https://giveth.io/project/love-for-iran
https://giveth.io/project/stand-up-for-iranians-stand-up-for-web3-inclusivity
https://giveth.io/project/relocating-web3-iranians
https://giveth.io/project/stand-up-for-woman-life-and-freedom-movement

**Comment by oyealmond** [comment] 2022-11-21 18:58
it should be great to have a MTM w some of these projects! @WhyldWanderer @NikolaCreatrix , and I think Jan may be a good date bc it will take time to contact the project owners. Tho your right this will need to double check to avoid scams...  yeah maybe this could be too risky, having in mind all the internet limitations, and government threads etc... 


Make some tweets would be great tho!  
We could work on the final projects list regarding Iran and draft some copies.
I looked & only found the ones you already posted @WhyldWanderer  related to the cause: 

https://giveth.io/project/love-for-iran
https://giveth.io/project/stand-up-for-iranians-stand-up-for-web3-inclusivity
https://giveth.io/project/relocating-web3-iranians
https://giveth.io/project/stand-up-for-woman-life-and-freedom-movement

should we move fwd and draft something? @laurenluz

**Comment by c0ric0ri** [comment] 2022-11-21 19:50
Well we could do both. Preparing some tweets for now, and also setting up the next MTM theme in January. Also could do a Twitter Space involving web3 contributors from Iran. That would be very interesting and cool to do.

The tweet threads now can highlight the projects, call to action for donations, explain a bit about what is happening in Iran, and maybe include some points about how web3 and decentralization are especially relevant in these cases.

**Comment by WhyldWanderer** [comment] 2022-11-21 22:05
You know... Ive been thinking about this and maybe its not the best idea to have the project owners come and represent these projects :/ We probably want to preserve their identities right?

**Comment by NikolaCreatrix** [comment] 2022-11-22 14:10
Hi @laurenluz , just catching up. 
That is really beautiful initiative. I think we can invite them to Twitter MTM space @oyealmond where they can keep their Twitter identity... Also, Twitter is better than discord because the discord event is meant for verified projects and not all of the new Iran projects are verified, in fact, most of them are not. Great job almond pulling them out. That's about the list of the projects we have listed :) 

Maybe to stay cautious and careful around this topic's whole stickiness and protect the project owners, we just need to be very smart about how we communicate this campaign to the public.

And Ashley has a good point about making sure that those projects are really legit, for the same reasons - haven't gone through verification therefore a detailed investigation process :)

Blog post & supportive sweets created for those projects sound great. Btw my personal impression is that the projects above  are legit.

**Comment by laurenluz** [comment] 2022-11-22 16:28
From comms call: - @GriffGreen 
- very few donation platforms can actually support these projects responding to the violence in Iran
- would be great to get blurbs about each project
- themed fundraising effort for a variety of projects can be done on a regular basis

We should be very careful that the projects are legit before we publicize them. And may need to be careful to protect the identity of project owners. - @WhyldWanderer 

Twitter space candiates: Amin Solani, people at consensus, coin iran media platform, 30 or so people in a tg group that @GriffGreen is part of that we could push comms to and get support from.

@NikolaCreatrix some great projects listed and can invite these project owners and impactful people in web3 space in a MTM-like but can still invite non-verified projects.

Option to set up twitter space on Dec 7 - @oyealmond to set it up, @GriffGreen to recommend folks

**Comment by c0ric0ri** [comment] 2022-12-02 22:47
Moving this to icebox as it was decided not to proceed with this campaign due to team security concerns.

**Closed** 2024-01-23 16:30 UTC
Labels: Epic
